### ISSUE TITLE
GNATColl: Free_Knowledge_Base not declared in Knowledge.

### ISSUE THREAD

**Issue by Blady-Com** [steve-cs/gnat-builder#13]
Hello,
When building GNATColl 20.2 I've got this issue:
gnatcoll-projects.adb:11313:20: "Free_Knowledge_Base" not declared in "Knowledge"
I've put the line in comment:
```
% diff -u gnatcoll-core-src/src/gnatcoll-projects.adb gnatcoll-core-build/src
--- gnatcoll-core-src/src/gnatcoll-projects.adb	2020-02-17 10:24:39.000000000 +0100
+++ gnatcoll-core-build/src/gnatcoll-projects.adb	2020-02-17 11:01:12.000000000 +0100
@@ -11310,7 +11310,7 @@
          On_Target => TS_Id);
       Host_Targets_List.Append
         (GPR.Knowledge.Normalized_Target (KB, TS_Id));
-      GPR.Knowledge.Free_Knowledge_Base (KB);
+      --  GPR.Knowledge.Free_Knowledge_Base (KB);
 
    end Set_Host_Targets_List;
```
HTH, Pascal.

**Comment by steve-cs** [comment]
This looks possibly like a sync problem between gnatcoll-core and gprbuild/gpr.  Have you built and installed the 20.2 gprbuild first?

**Comment by Blady-Com** [comment]
Hello Steve, I took the GPR coming with the GNAT distro.
Right, GPR.Knowledge.Free_Knowledge_Base is also declared in GPRbuild.
Thanks, Pascal.
