### ISSUE TITLE
Alt-Ergo, CVC4 and Z3 are not build.

### ISSUE THREAD

**Issue by Blady-Com** [steve-cs/gnat-builder#16]
Hello,

The provers used by SPARK: Alt-Ergo, CVC4 and Z3 are not build.
Here are some instructions to build them:
Alt-Ergo:
```
% cd /opt/spark2014-build/alt-ergo/sources
% ./configure alt-ergo --prefix=/opt/spark2014-build/install
% make alt-ergo       
% make install-bin
```
CVC4 (boost and java dependencies):
```
% cd /opt/spark2014-build/cvc4
% ./contrib/get-antlr-3.4  # realpath missing -> fix needed
% ./configure.sh --prefix=/opt/spark2014-build/install --name=_build
% cd _build
% make
% make install
```
Z3:
```
% cd /opt/spark2014-build/z3
% python scripts/mk_make.py --prefix=/opt/spark2014-build/install
% cd build
% make
% make install
```
Do I propose some makefile changes or else do you want to modify it at your convenience?

Regards, Pascal.

**Comment by steve-cs** [comment]
I've been meaning to do this, or at least take a look.  While the provers were in separate repositories and Adacore was not taking any bug reports against them and instead referring any/all issues upstream I was preferring to use system (Debian/Ubuntu) built provers.  That worked well enough for me. 

As Adacore appears to maintaining in tree, I should probably at least provide an option for building spark2014-provers, if not building and installing them by default as part of "make spark2014 spark2014-install".  I'll take a look at current Adacore documentation and see what makes best sense to me.

**Comment by steve-cs** [comment]
I'm stumbling over dependency issues right away.  First one is Alt-Ergo configure depends on dune.  dune doesn't exist in Ubuntu LTS 18.04.  I'm hesitating on installing dune via opam or building dune directly or moving to a more recent non-LTS version of Ubuntu, etc.

Summary: I'm concerned that this is not as simple as I was hoping.

**Comment by steve-cs** [comment]
@Blady-Com, please see recent commit https://github.com/steve-cs/gnat-builder/commit/bc48b865e58493507fa5adbeab53ac43e395199a which is my first draft at a framework.  Let me know what you think and how far you get.

**Comment by Blady-Com** [comment]
> Le 24 mars 2020 à 00:51, Steve Johnson <notifications@github.com> a écrit :
> 
> @Blady-Com, please see recent commit bc48b86 which is my first draft at a framework. Let me know what you think and how far you get.

Hello Steve,

The changes seem correct to me.
The prefix option let us to choose the final install folder or the intermediate install folder in spark build folder.

Thanks, Pascal.
https://blady.pagesperso-orange.fr
