### ISSUE TITLE
Run failed: GNAT Bootstrap CI - master (934959d)

### ISSUE THREAD

**Issue by Blady-Com** [steve-cs/gnat-builder#17]
Hello,
I receive many e-mails with this object or similar:
`Run failed: GNAT Bootstrap CI - master (934959d)`
Is there a way to avoid them?
Thanks Pascal.

**Comment by steve-cs** [comment]
At the bottom of each message should be a clue on why you are getting notifications of build failures. The recent failures are because of two unrelated issues, one of which has been resolved and one still exists.

Specifically I received the above notification because:

> You are receiving this because this workflow ran on your branch.
> Manage your GitHub Actions notifications here.

Edit: I presume that github actions are running on your fork.  If you edit or delete gnat-builder/.github/workflows/bootstrap.yml in your fork then I suspect the notifications that you are seeing will go away.

**Comment by Blady-Com** [comment]
Thanks Steve for your quick answer,
I'm not aware of Github actions.
I've several git branches.
Should I remove bootstrap.yml from all of them? or only master branch?
If I modify master branch then I would have conflicts with your master branch when updating it later?
Is there a way to tell bootstrap.yml to run only on your repo for instance?
If not possible I will nevertheless disable e-mail notifications.
Take care you and your family in this period of uncertainty, Pascal.

**Comment by steve-cs** [comment]
>Should I remove bootstrap.yml from all of them? or only master branch?

At the current time I only use github actions to test a nightly linux bootstrap.  As this is likely of no interest or use to you, it's probably simpler for you to delete it in all your branches.

>If I modify master branch then I would have conflicts with your master branch when updating it later?

When I change the bootstrap.yml it might end up throwing a merge conflict which you would resolve by choosing your version over my new one (reject my change).  Worst case is to accept my new version in the merge and then delete the file again.

>Is there a way to tell bootstrap.yml to run only on your repo for instance?

Good question.  Yes, if I created a second repository or a separate development/CI branch that included the github actions and removed them from the main repo and/or master branch.  That's what I probably should do, making it my management problem not yours.  I'll look into it to see what feels best.  I had completely ignored this before.

> Take care you and your family in this period of uncertainty

You as well.

**Comment by steve-cs** [comment]
I've removed the github workflow bootstrap.yml and updated the status badge in the README to point to the action-test repository.  These changes have been made in both the master and cs-20 branches.  This should fix the issue.
