### ISSUE TITLE
Unknown project file: "gnatcoll_sql".

### ISSUE THREAD

**Issue by Blady-Com** [steve-cs/gnat-builder#5]
Hello Steve,

I've tried your last makefile with os support. It's really good :-)
Up to now I've simply run (without any change):
$ make os=darwin

But I've got this error:
make -C gnatcoll-db-build/gnatcoll_db2ada
gprbuild -p -m --target=x86_64-darwin  -j0 -XLIBRARY_TYPE=static -XXMLADA_BUILD=static -XGPR_BUILD=static -XGNATCOLL_VERSION=0.0 -XBUILD=PROD  gnatcoll_db2ada.gpr
gnatcoll_db2ada.gpr:25:06: unknown project file: "gnatcoll_sql"

Seems that gnatcoll_sql have to be installed before.
Have the same behaviour?
What may I do?
Thanks, Pascal.

**Comment by steve-cs** [comment]
> I've tried your last makefile with os support. It's really good :-)

It was my first draft in anticipation of supporting external build dependencies in redhat/centos that differ or might differ from debian/ubuntu.  Someday I might actually get around to doing real centos releases.

> Seems that gnatcoll_sql have to be installed before.

Yes, that's true.  Adacore has inter sub-module dependencies within gnatcoll.  These dependencies are not explicitly stated in Makefile dependencies.  If building from scratch (i.e. an existing gnatcoll is not installed) then pieces of gnatcoll have to be built and installed in a specific order.  Please see the "all-gnat-bootstrap" target for how it bootstraps gnatcoll.

I imagine that something like "$make os=darwin gnatcoll-sql gnatcoll-sql-install" should get you past your specific issue.

**Comment by Blady-Com** [comment]
I got it, I was wondering about bootstrap targets.
I will follow you advice, thanks Pascal.

**Comment by steve-cs** [comment]
bootstrap targets are internal, meant to be called by "make release".  This eliminates any dependencies on Adacore community releases, i.e. no possibility of GPL (without linking excpetion) contamination.

>  PS: is the following declaration correct in all-gnat-bootstrap? As it builds all at one time:

Yes, it is correct.  gnatcoll-db-build doesn't actually build anything.  It just creates the gnat-db-build directory, populates it with source code and runs the needed setup / configuration.  The actual build and installs of sub-modules of gnatcoll-db follow.
