### ISSUE TITLE
Libaadalang: license of withed unit "GNATCOLL.Refcount" may be inconsistent.

### ISSUE THREAD

**Issue by Blady-Com** [steve-cs/gnat-builder#6]
Hello Steve,

I've the following issue with libadalang:
   [Ada]          langkit_support-tree_traversal_iterator.adb
langkit_support-tree_traversal_iterator.ads:24:14: warning: license of withed unit "GNATCOLL.Refcount" may be inconsistent
   compilation of langkit_support-tree_traversal_iterator.adb failed

Is there a way to avoid warning processed as errors?

Thanks, Pascal.

**Comment by steve-cs** [comment]
I don't see this warning in my builds of libadalang stable.   I suspect that you might be mixing Adacore community and github sources or stumbling over something new in master branch.  I do not use the community/GPL toolchain in any manner.  Might be a question for Adacore.

I don't have an opinion on the best way to patch in non standard compiler options.

**Comment by Blady-Com** [comment]
You guess right, I run GNAT Community 2019. I haven't found a way to add compiler options in the tool ada/manage.py. I'll ask to AdaCore.
Thanks Pascal.
